### ISSUE TITLE
Provide updated install instructions

### ISSUE THREAD

**Issue by sebasguts** [oscar-system/oscar-website#25]

**Comment by fingolfin** [comment]
This is still badly needed. Esp. Since https://oscar.computeralgebra.de/install/ refers to Julia 1.1.0.

**Comment by fingolfin** [comment]
Ping @wbhart @fieker @micjoswig @ThomasBreuer @wdecker @rbehrends @mohamed-barakat @frankluebeck So, who is going to take over maintenance of the website from Sebastian? And will update the install instructions among other things?

I just noticed that https://oscar.computeralgebra.de/credits/ still lists @sebasguts as being financed by the SFB (till 2020). There are many more things on the website which are out of date. A simple fix of course is to just delete them, but that may not always be the best...

**Comment by wbhart** [comment]
I've been doing a little bit here and there when I find time. I'll now go ahead and fix the issue with @sebasguts being listed in the wrong place, since you point it out.

When we actually have a working Oscar that can be installed, I will update the install instructions.

Currently no one is maintaining the docker images, and I don't intend to. So I recommend we simply remove these as they should no longer be needed. However, others disagree with me on that, so perhaps a decision could be taken on that before I remove them (which I will not do until Oscar installs for all of us without trouble on at least Linux and Mac).

**Comment by wbhart** [comment]
Actually, I've taken a look and I think its just fine. There are two ways of reading it. The first is the way you read it. The second is that this is a list of people who were financed by the TRR in the first period of 4 years. I'm inclined to not alter it. But if people feel strongly about it, let me know and I will make the change.

**Comment by mohamed-barakat** [comment]
I currently have a master student paid for software development whom I will ask to temporarily maintain the website until I hire a successor of Sebastian Gutsche.

**Comment by fingolfin** [comment]
@fieker and me just overhauled the installation page from ground up
